path: 'C:\Users\LQA\Desktop\class\Lxx\dataset'
train: 'C:\Users\LQA\Desktop\class\Lxx\dataset\images\train'
val: 'C:\Users\LQA\Desktop\class\Lxx\dataset\images\val'
names:
  0: With_Helmet
  1: Without_Helmet